### ISSUE TITLE
R3D does not have version tags or releases

### ISSUE THREAD

**Issue by raovgarimella** [devonmpowell/r3d#26]
R3D currently is not tagged with version numbers and it would be good to have that. We use a semantic versioning sytem of the form A.b.c where c is updated for patches, b for new features and major reworking of algorithms and A for interface changes.

**Comment by devonmpowell** [comment]
Yes, this is a good idea. I will get to this as soon as I have time.

**Comment by devonmpowell** [comment]
I have added a versioning tag, starting with 2.1.0 (major version 2 , since this algorithm is different from the one originally published, minor version 1 due to recent work by @raovgarimella).
If we are happy with this version, we can create a release. Not sure if there are any pending bugfixes, etc. at the moment.
Cheers,
Devon
