### ISSUE TITLE
Support non-planar faces?

### ISSUE THREAD

**Issue by dionhaefner** [devonmpowell/r3d#34]
I want to apply `r3d` to a mesh that contains some non-planar faces. Example cell:

<img width="374" alt="Screenshot 2023-07-26 at 12 46 51" src="https://github.com/devonmpowell/r3d/assets/11994217/5a204732-9060-4821-8b69-9bceee750f3b">

This triggers the following exit condition in `r3d_init_poly`:

```c
// return if we were given an invalid poly
if (minvperf < 3) return 0;
```

Is there a simple way around this?

**Comment by devonmpowell** [comment]
By design, r3d does not support non-planar faces.  To ensure robustness of the clipping operations in finite precision, every polyhedron in r3d must have a 3-connected edge graph. Your graph appears to have a vertex with only two edges, hence the error.

The way around it is to add extra edges to the cell and make it a complete polyhedron, before calling `r3d_init_poly`.  What is your use case? Maybe there is an easy way to add dummy edges/vertices?

**Comment by dionhaefner** [comment]
Thanks. I agree with the solution to split non-planar faces into several planar ones. I was wondering whether this could be handled within `r3d`, i.e., if `minvperf < 3` add additional faces until the condition is fulfilled?

**Comment by dionhaefner** [comment]
I realized that non-planar faces are not uniquely defined by their vertices so probably an unsolvable problem in general. I fixed it by computing the convex hull of each polyhedron and passing that to `r3d`, works like a charm.

**Comment by devonmpowell** [comment]
Ah yes, I would say the same - it would be hard to include some type of automatic polyhedron completion in `r3d_init_poly` that is sufficiently general to satisfy everyone's idea of how it should work.  Glad you found a solution.
